plugins {
    alias libs.plugins.fabric.loom
}

dependencies {
    minecraft libs.minecraft

    implementation libs.fabric.loader
    implementation (libs.fabric.api) {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }

    implementation project(":Common")
    compileOnly libs.jetbrains.annotations

    compileOnly libs.autoservice.annotations
    annotationProcessor libs.autoservice

    compileOnly libs.sparkweave
    compileOnly libs.sparkweave.fabric
    compileOnly (libs.resourcefulconfig.fabric) {
        exclude group: "net.fabricmc", module: "fabric-loader"
    }
    compileOnly libs.commonnetworking.fabric

    compileOnly libs.trinkets.fabric
    runtimeOnly libs.trinkets.fabric
    compileOnly libs.bundles.cca.fabric
    runtimeOnly libs.bundles.cca.fabric
    compileOnly libs.modmenu.fabric
    compileOnly libs.figura.fabric
    compileOnly libs.jei.fabric

    compileOnly variantOf(libs.emi.fabric) { classifier 'api' }

}

loom {
    mods {
        "${mod_id}" {
            sourceSet("main")
        }
    }
    mixin {
        useLegacyMixinAp.set(false)
    }

    runs {
        configureEach {
            ideConfigGenerated(true)
            it.property('mixin.debug', 'true')
            it.property('sparkweave.debug', 'true')
        }

        client {
            client()
            setConfigName("Fabric Client")
            runDir("run")

            if (rootProject.hasProperty('mc_uuid')) {
                programArgs("--uuid", rootProject.mc_uuid)
            }

            if (rootProject.hasProperty('mc_username')) {
                programArgs("--username", rootProject.mc_username)
            }

            if (rootProject.hasProperty('mc_java_agent_path')) {
                vmArg("-javaagent:${rootProject.mc_java_agent_path}")
            }
        }

        server {
            server()
            setConfigName("Fabric Server")
            runDir("run/server")
        }
    }
}

jar {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(":Common").sourceSets.main.output
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from project(":Common").sourceSets.main.resources
}

