plugins {
	alias libs.plugins.moddevgradle
}

neoForge.neoFormVersion = libs.versions.neoform.get()

dependencies {
	compileOnly libs.bundles.mixin
	annotationProcessor libs.mixin.extras
	compileOnly libs.jetbrains.annotations
	compileOnly libs.autoservice.annotations

	compileOnly libs.sparkweave
	compileOnly libs.resourcefulconfig
	compileOnly libs.commonnetworking

	compileOnly libs.figura

	compileOnly variantOf(libs.emi) { classifier 'api' }

	testImplementation libs.junit.api
	testRuntimeOnly libs.junit.launcher
}

neoForge {
}

test {
	useJUnitPlatform()
}
