plugins {
    alias libs.plugins.moddevgradle
}

// need this before dependencies because it configures the plugin and creates additionalRuntimeClasspath configuration
neoForge.version = libs.versions.neoforge.get()

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    compileOnly project(":Common")

    compileOnly libs.autoservice.annotations
    annotationProcessor libs.autoservice

    implementation libs.sparkweave.neoforge
    implementation libs.resourcefulconfig.neoforge
    implementation libs.commonnetworking.neoforge
    implementation libs.curios.neoforge
    implementation libs.caelus.neoforge

    compileOnly libs.figura.neoforge
//    localRuntime libs.figura.neoforge
//    localRuntime libs.bundles.figura.runtime

    compileOnly variantOf(libs.emi.neoforge) { classifier 'api' }

    testImplementation libs.neoforge.testframework
}

test {
    useJUnitPlatform()
}

neoForge {
    mods {
        "${mod_id}" {
            sourceSet(project(":Common").sourceSets.main)
            sourceSet(sourceSets.main)
        }
    }

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
            // The markers can be added/remove as needed separated by commas.
            // "SCAN": For mods scan.
            // "REGISTRIES": For firing of registry events.
            // "REGISTRYDUMP": For getting the contents of all registries.
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'mixin.debug', 'true'
            systemProperty 'sparkweave.debug', 'true'

            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
            gameDirectory = project.file('run')

            if (rootProject.hasProperty('mc_java_agent_path')) {
                jvmArgument("-javaagent:${rootProject.mc_java_agent_path}")
            }
        }

        client {
            client()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

            if (project.hasProperty('mc_uuid')) {
                programArgument "--uuid=${project.findProperty('mc_uuid')}"
            }

            if (project.hasProperty('mc_username')) {
                programArgument "--username=${project.findProperty('mc_username')}"
            }
        }

        server {
            server()
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id

            programArgument '--nogui'
        }

        data {
            data()
            programArguments.addAll('--mod', 'sparkweave', '--mod', project.mod_id, '--all', '--flat', '--output', file('src/generated/resources').absolutePath, '--existing', file('src/main/resources').absolutePath)
        }
    }

    unitTest {
        enable()

        testedMod = mods."${mod_id}"
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

tasks.named("compileJava", JavaCompile) {
    source(project(":Common").sourceSets.main.allJava)
}

tasks.named("javadoc", Javadoc) {
    source(project(":Common").sourceSets.main.allJava)
}

tasks.named("sourcesJar", Jar) {
    from(project(":Common").sourceSets.main.allSource)
}

processResources {
    from project(":Common").sourceSets.main.resources
}
